# Generated by Django 6.0.4 on 2026-05-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('days', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1, null=True)),
                ('time', models.TimeField(null=True)),
                ('max_attendance', models.IntegerField(default=999, null=True)),
                ('is_routine', models.IntegerField(default=1, null=True)),
                ('is_active', models.BooleanField(null=True)),
            ],
        ),
    ]
