# Generated by Django 6.0.5 on 2026-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
