# Generated by Django 6.0.5 on 2026-05-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_members_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('remaining_sessions', models.IntegerField(default=-1)),
                ('is_paused', models.BooleanField(default=False)),
                ('pause_start_date', models.DateTimeField(blank=True, null=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.members')),
            ],
        ),
    ]
