# Generated by Django 6.0.4 on 2026-05-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='active_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='pause_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
