# Generated by Django 6.0.4 on 2026-05-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_membership_active_until_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='member_id',
            new_name='member',
        ),
    ]
