# Generated by Django 6.0.4 on 2026-05-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_member_id_membership_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='member',
        ),
        migrations.AddField(
            model_name='membership',
            name='member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
